# SwiftLint Configuration
# Relaxed rules to allow tests to run

disabled_rules:
  - type_body_length
  - file_length
  - function_body_length
  - identifier_name
  - line_length
  - cyclomatic_complexity
  - large_tuple

excluded:
  - build
  - fastlane
  - fastlane-output
  - .git
  - .claude
  - "*.generated.swift"
