name: Murmur

options:
  bundleIdPrefix: com.cornelius-bell
  deploymentTarget:
    iOS: "18.6"
  developmentLanguage: en
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.50"
    CURRENT_PROJECT_VERSION: "100"
    ENABLE_HARDENED_RUNTIME: NO
    DEVELOPMENT_TEAM: HK6R36PLNR
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_APPINTENTS_METADATA: YES
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""

targets:
  Murmur:
    type: application
    platform: iOS
    sources:
      - path: Murmur
        excludes:
          - "**/*.md"
          - "**/Info.plist"
          - "MurmurTests"
    info:
      path: Murmur/Resources/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        ITSAppUsesNonExemptEncryption: false
        LSApplicationCategoryType: public.app-category.healthcare-fitness
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiresPersistentWiFi: false
        UIStatusBarHidden: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSCalendarsFullAccessUsageDescription: Murmur can read from your calendar to help you track exertion.
        NSHealthClinicalHealthRecordsShareUsageDescription: Murmur may write symptom data to Health in the future to integrate with your health records.
        NSHealthShareUsageDescription: Murmur can read your health data to add private context to your entries.
        NSHealthUpdateUsageDescription: Murmur may write symptom data to Health in the future to integrate with your health records.
        NSLocationWhenInUseUsageDescription: Optionally, to add location to your entries.
        NSMicrophoneUsageDescription: Murmur needs microphone access for voice commands to log symptoms hands-free.
        NSSpeechRecognitionUsageDescription: Murmur uses speech recognition to allow hands-free symptom logging via voice commands.
        NSSupportsLiveActivitiesFrequentUpdates: true
        NSUserActivityTypes:
          - LogSymptomIntent
          - OpenAddEntryIntent
          - OpenAddActivityIntent
          - GetRecentEntriesIntent
          - GetSymptomsBySeverityIntent
          - GetDailySummaryIntent
          - CountSymptomsIntent
        BGTaskSchedulerPermittedIdentifiers:
          - com.aidancb.Murmur.autobackup
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cornelius-bell.Murmur
        INFOPLIST_FILE: Murmur/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Murmur/Murmur.entitlements
        MARKETING_VERSION: "1.40"
        CURRENT_PROJECT_VERSION: "100"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_OTHER_FLAGS: --enable-icon-stack-fallback-generation=disabled
        ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_PREVIEWS: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
    dependencies:
      - target: MurmurWidgetsExtension
    preBuildScripts:
      - script: |
          # Run SwiftLint if installed
          if which swiftlint >/dev/null; then
            swiftlint
          fi
        name: SwiftLint
        basedOnDependencyAnalysis: false
        showEnvVars: false

  MurmurWidgetsExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: MurmurWidgets
        excludes:
          - "**/*.md"
          - "**/Info.plist"
    info:
      path: MurmurWidgets/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: Murmur Widgets
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cornelius-bell.Murmur.MurmurWidgets
        PRODUCT_NAME: MurmurWidgets
        PRODUCT_DISPLAY_NAME: Murmur Widgets
        MARKETING_VERSION: "1.40"
        CURRENT_PROJECT_VERSION: "100"
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        GENERATE_INFOPLIST_FILE: YES

  MurmurTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MurmurTests
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cornelius-bell.MurmurTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Murmur.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Murmur"
        BUNDLE_LOADER: "$(TEST_HOST)"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Murmur

  MurmurUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: MurmurUITests
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cornelius-bell.MurmurUITests
        TEST_TARGET_NAME: Murmur
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Murmur

schemes:
  Murmur:
    build:
      targets:
        Murmur: all
        MurmurWidgetsExtension: all
        MurmurTests: [test]
        MurmurUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Murmur
      targets:
        - name: MurmurTests
        - name: MurmurUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  MurmurWidgetsExtension:
    build:
      targets:
        MurmurWidgetsExtension: all
    run:
      config: Debug

  MurmurUITests:
    build:
      targets:
        Murmur: all
        MurmurUITests: [test]
    test:
      config: Debug
      targets:
        - name: MurmurUITests
      commandLineArguments:
        "-CaptureTestScreenshots":
          enabled: true
